---
    # This workflow generates the output and pushes it to main branch

    name: Generate Output

    on:
      schedule:
        - cron: "0 0 * * *"
      push:
        branches: ["main"]

    jobs:
      create-matrix:
        runs-on: ubuntu-latest
        outputs:
          matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Generate matrix with generate-matrix.sh
            run: chmod +x .github/workflows/cvarlist-generate-matrix.sh; .github/workflows/cvarlist-generate-matrix.sh

          - name: Set Matrix
            id: set-matrix
            run: |
              shortnamearray=$(cat shortnamearray.json)
              echo "${shortnamearray}"
              echo -n "matrix=${shortnamearray}" >> $GITHUB_OUTPUT

      generate-output:
        needs: create-matrix
        continue-on-error: true
        runs-on: ubuntu-latest

        strategy:
          matrix: ${{ fromJSON(needs.create-matrix.outputs.matrix) }}

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup SteamCMD
            uses: CyberAndrii/setup-steamcmd@v1.1.5

          - name: Run get_cvars.sh
            run: ./get_cvars.sh ${{ matrix.shortname }}

          - name: Get current date
            id: date
            run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

          - name: Push to main branch
            uses: Automattic/action-commit-to-branch@master
            with:
              branch: "main"
              commit_message: "GitHub Actions build: ${{ steps.date.outputs.date }}"
            env:
              GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
